#!/bin/bash

if [ ! -d "/var/mobile/Documents/Ethereal" ]; then
	mkdir /var/mobile/Documents/Ethereal
	chown -R mobile:mobile /var/mobile/Documents/Ethereal
fi

if [ ! -d "/fs/jb/Library/Caches/com.nito.Ethereal" ]; then

	mkdir /fs/jb/Library/Caches/com.nito.Ethereal
	chown -R mobile:admin /fs/jb/Library/Caches/com.nito.Ethereal
fi

if [ ! -L "/var/mobile/Documents/ScreenRecording" ]; then
    
    ln -s /var/mobile/Media/DCIM/100APPLE /var/mobile/Documents/ScreenRecording
fi
